<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-19T12:23:26 EET" name="Suite" finished-at="2023-12-19T12:23:44 EET" duration-ms="18636">
    <groups>
      <group name="GuestUser">
        <method signature="RegistredBySavedCCSavedAddress.placeOrderRegestredCard(java.util.HashMap)[pri:0, instance:Boohoo.BHM.tests.RegistredBySavedCCSavedAddress@d62fe5b]" name="placeOrderRegestredCard" class="Boohoo.BHM.tests.RegistredBySavedCCSavedAddress"/>
      </group> <!-- GuestUser -->
      <group name="Regression">
        <method signature="RegistredBySavedCCSavedAddress.placeOrderRegestredCard(java.util.HashMap)[pri:0, instance:Boohoo.BHM.tests.RegistredBySavedCCSavedAddress@d62fe5b]" name="placeOrderRegestredCard" class="Boohoo.BHM.tests.RegistredBySavedCCSavedAddress"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="RegistredBySavedCCSavedAddress.placeOrderRegestredCard(java.util.HashMap)[pri:0, instance:Boohoo.BHM.tests.RegistredBySavedCCSavedAddress@d62fe5b]" name="placeOrderRegestredCard" class="Boohoo.BHM.tests.RegistredBySavedCCSavedAddress"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2023-12-19T12:23:26 EET" name="Registred user with saved cards and addresses" finished-at="2023-12-19T12:23:44 EET" duration-ms="18636">
      <class name="Boohoo.BHM.tests.RegistredBySavedCCSavedAddress">
        <test-method is-config="true" signature="lunchWebSite()[pri:0, instance:Boohoo.BHM.tests.RegistredBySavedCCSavedAddress@d62fe5b]" started-at="2023-12-19T12:23:26 EET" name="lunchWebSite" finished-at="2023-12-19T12:23:31 EET" duration-ms="5575" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchWebSite -->
        <test-method signature="placeOrderRegestredCard(java.util.HashMap)[pri:0, instance:Boohoo.BHM.tests.RegistredBySavedCCSavedAddress@d62fe5b]" started-at="2023-12-19T12:23:31 EET" name="placeOrderRegestredCard" data-provider="getData" finished-at="2023-12-19T12:23:35 EET" duration-ms="3742" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{cvc=737, country=Deutschland, cartNumber=4111111111111111, userPassword=Test1234, city=Berlin, address1=Abbestr. 2-12, userEmail1=y.bartash+de73@astoundcommerce.com, postal=10587, cartName=Visa, expDate=0330, confirmationMessage=DANKE FÜR DEINE BESTELLUNG}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Boohoo.BHM.tests.RegistredBySavedCCSavedAddress.placeOrderRegestredCard(RegistredBySavedCCSavedAddress.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrderRegestredCard -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Boohoo.BHM.tests.RegistredBySavedCCSavedAddress@d62fe5b]" started-at="2023-12-19T12:23:36 EET" name="tearDown" finished-at="2023-12-19T12:23:36 EET" duration-ms="140" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lunchWebSite()[pri:0, instance:Boohoo.BHM.tests.RegistredBySavedCCSavedAddress@d62fe5b]" started-at="2023-12-19T12:23:36 EET" name="lunchWebSite" finished-at="2023-12-19T12:23:40 EET" duration-ms="4266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchWebSite -->
        <test-method signature="placeOrderRegestredCard(java.util.HashMap)[pri:0, instance:Boohoo.BHM.tests.RegistredBySavedCCSavedAddress@d62fe5b]" started-at="2023-12-19T12:23:40 EET" name="placeOrderRegestredCard" data-provider="getData" finished-at="2023-12-19T12:23:44 EET" duration-ms="3948" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{cvc=737, country=Deutschland, cartNumber=5555341244441115, userPassword=Test1234, city=Berlin, address1=Abbestr. 2-12, userEmail1=y.bartash+de73@astoundcommerce.com, postal=10587, cartName=Master Card, expDate=0330, confirmationMessage=DANKE FÜR DEINE BESTELLUNG}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Boohoo.BHM.tests.RegistredBySavedCCSavedAddress.placeOrderRegestredCard(RegistredBySavedCCSavedAddress.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- placeOrderRegestredCard -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Boohoo.BHM.tests.RegistredBySavedCCSavedAddress@d62fe5b]" started-at="2023-12-19T12:23:44 EET" name="tearDown" finished-at="2023-12-19T12:23:44 EET" duration-ms="137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Boohoo.BHM.tests.RegistredBySavedCCSavedAddress -->
    </test> <!-- Registred user with saved cards and addresses -->
  </suite> <!-- Suite -->
</testng-results>
